/**
 * PHASE3_PLAN.md Stage 1 — the parity harness. Composes the engine's real per-hit damage
 * (resolveHitComposedDps, gear-aware via its externalStats param — see resolveHitComposedDps.js's
 * own jsdoc) against calcTeamStats.js's real, equipment-inclusive RAW tier (equipment-only, no team
 * buffs — the cleanest solo-comparable slice, since it skips the rotation order-search,
 * cross-character buff routing, DOT, and energy-cycle gating that PHASE3_PLAN.md's Stage 0 audit
 * found have no engine equivalent yet).
 *
 * This does NOT assert close numeric equality — the two models are legitimately different (real
 * per-hit composition vs. a single flat totalMult%), and this file's own header note already
 * establishes that divergence is often a real precision IMPROVEMENT, not a bug. Every case logs its
 * real numbers (visible in `npx vitest run --reporter=verbose` output) for PHASE3_PLAN.md Stage 2's
 * triage pass to consume — sanity bounds only (both positive, finite), not tolerance assertions.
 *
 * Covers all 56 characters with a converted `.blocks.js` file (Jingran excluded — unreleased, no
 * rotation data, per every prior Phase 2/3 note).
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { calcTeamStats } from '../features/teams/calcTeamStats.js';
import { CHARACTER_DATA, CHARACTER_ROTATIONS } from '../data/characters.js';
import { WEAPON_DATA } from '../data/weapons.js';
import { ECHO_SETS } from '../data/echoes.js';
import { applyFullEchoSet, getWeaponPv } from '../features/teams/calcEngine.js';
import { resolveHitComposedDps } from '../engine/resolveHitComposedDps.js';
import { deriveStepsFromRotation } from '../engine/rotationSimulator.js';

// name (matches CHARACTER_DATA's own key exactly) -> { file, exportName } for every converted
// character's characterBlocks/*.blocks.js — generated by listing the directory and each file's own
// `SOURCE`/exported const, not hand-typed, so it can't silently drift from what Phase 2 actually built.
const BLOCK_FILES = [
  { name: 'Aalto', file: 'aalto.blocks.js', exportName: 'AALTO_BLOCKS' },
  { name: 'Aemeath', file: 'aemeath.blocks.js', exportName: 'AEMEATH_BLOCKS' },
  { name: 'Augusta', file: 'augusta.blocks.js', exportName: 'AUGUSTA_BLOCKS' },
  { name: 'Baizhi', file: 'baizhi.blocks.js', exportName: 'BAIZHI_BLOCKS' },
  { name: 'Brant', file: 'brant.blocks.js', exportName: 'BRANT_BLOCKS' },
  { name: 'Buling', file: 'buling.blocks.js', exportName: 'BULING_BLOCKS' },
  { name: 'Calcharo', file: 'calcharo.blocks.js', exportName: 'CALCHARO_BLOCKS' },
  { name: 'Camellya', file: 'camellya.blocks.js', exportName: 'CAMELLYA_BLOCKS' },
  { name: 'Cantarella', file: 'cantarella.blocks.js', exportName: 'CANTARELLA_BLOCKS' },
  { name: 'Carlotta', file: 'carlotta.blocks.js', exportName: 'CARLOTTA_BLOCKS' },
  { name: 'Cartethyia', file: 'cartethyia.blocks.js', exportName: 'CARTETHYIA_BLOCKS' },
  { name: 'Changli', file: 'changli.blocks.js', exportName: 'CHANGLI_BLOCKS' },
  { name: 'Chisa', file: 'chisa.blocks.js', exportName: 'CHISA_BLOCKS' },
  { name: 'Chixia', file: 'chixia.blocks.js', exportName: 'CHIXIA_BLOCKS' },
  { name: 'Ciaccona', file: 'ciaccona.blocks.js', exportName: 'CIACCONA_BLOCKS' },
  { name: 'Danjin', file: 'danjin.blocks.js', exportName: 'DANJIN_BLOCKS' },
  { name: 'Denia', file: 'denia.blocks.js', exportName: 'DENIA_BLOCKS' },
  { name: 'Encore', file: 'encore.blocks.js', exportName: 'ENCORE_BLOCKS' },
  { name: 'Galbrena', file: 'galbrena.blocks.js', exportName: 'GALBRENA_BLOCKS' },
  { name: 'Hiyuki', file: 'hiyuki.blocks.js', exportName: 'HIYUKI_BLOCKS' },
  { name: 'Iuno', file: 'iuno.blocks.js', exportName: 'IUNO_BLOCKS' },
  { name: 'Jianxin', file: 'jianxin.blocks.js', exportName: 'JIANXIN_BLOCKS' },
  { name: 'Jinhsi', file: 'jinhsi.blocks.js', exportName: 'JINHSI_BLOCKS' },
  { name: 'Jiyan', file: 'jiyan.blocks.js', exportName: 'JIYAN_BLOCKS' },
  { name: 'Lingyang', file: 'lingyang.blocks.js', exportName: 'LINGYANG_BLOCKS' },
  { name: 'Lucilla', file: 'lucilla.blocks.js', exportName: 'LUCILLA_BLOCKS' },
  { name: 'Lucy', file: 'lucy.blocks.js', exportName: 'LUCY_BLOCKS' },
  { name: 'Lumi', file: 'lumi.blocks.js', exportName: 'LUMI_BLOCKS' },
  { name: 'Lupa', file: 'lupa.blocks.js', exportName: 'LUPA_BLOCKS' },
  { name: 'Luuk Herssen', file: 'luukherssen.blocks.js', exportName: 'LUUK_HERSSEN_BLOCKS' },
  { name: 'Lynae', file: 'lynae.blocks.js', exportName: 'LYNAE_BLOCKS' },
  { name: 'Mornye', file: 'mornye.blocks.js', exportName: 'MORNYE_BLOCKS' },
  { name: 'Mortefi', file: 'mortefi.blocks.js', exportName: 'MORTEFI_BLOCKS' },
  { name: 'Phoebe', file: 'phoebe.blocks.js', exportName: 'PHOEBE_BLOCKS' },
  { name: 'Phrolova', file: 'phrolova.blocks.js', exportName: 'PHROLOVA_BLOCKS' },
  { name: 'Qingxiao', file: 'qingxiao.blocks.js', exportName: 'QINGXIAO_BLOCKS' },
  { name: 'Qiuyuan', file: 'qiuyuan.blocks.js', exportName: 'QIUYUAN_BLOCKS' },
  { name: 'Rebecca', file: 'rebecca.blocks.js', exportName: 'REBECCA_BLOCKS' },
  { name: 'Roccia', file: 'roccia.blocks.js', exportName: 'ROCCIA_BLOCKS' },
  { name: 'Rover: Electro', file: 'roverElectro.blocks.js', exportName: 'ROVER_ELECTRO_BLOCKS' },
  { name: 'Rover: Aero', file: 'roveraero.blocks.js', exportName: 'ROVER_AERO_BLOCKS' },
  { name: 'Rover: Havoc', file: 'roverhavoc.blocks.js', exportName: 'ROVER_HAVOC_BLOCKS' },
  { name: 'Rover: Spectro', file: 'roverspectro.blocks.js', exportName: 'ROVER_SPECTRO_BLOCKS' },
  { name: 'Sanhua', file: 'sanhua.blocks.js', exportName: 'SANHUA_BLOCKS' },
  { name: 'Shorekeeper', file: 'shorekeeper.blocks.js', exportName: 'SHOREKEEPER_BLOCKS' },
  { name: 'Sigrika', file: 'sigrika.blocks.js', exportName: 'SIGRIKA_BLOCKS' },
  { name: 'Suisui', file: 'suisui.blocks.js', exportName: 'SUISUI_BLOCKS' },
  { name: 'Taoqi', file: 'taoqi.blocks.js', exportName: 'TAOQI_BLOCKS' },
  { name: 'Verina', file: 'verina.blocks.js', exportName: 'VERINA_BLOCKS' },
  { name: 'Xiangli Yao', file: 'xianglyao.blocks.js', exportName: 'XIANGLI_YAO_BLOCKS' },
  { name: 'Yangyang', file: 'yangyang.blocks.js', exportName: 'YANGYANG_BLOCKS' },
  { name: 'Yangyang: Xuanling', file: 'yangyangxuanling.blocks.js', exportName: 'YANGYANG_XUANLING_BLOCKS' },
  { name: 'Yinlin', file: 'yinlin.blocks.js', exportName: 'YINLIN_BLOCKS' },
  { name: 'Youhu', file: 'youhu.blocks.js', exportName: 'YOUHU_BLOCKS' },
  { name: 'Yuanwu', file: 'yuanwu.blocks.js', exportName: 'YUANWU_BLOCKS' },
  { name: 'Zani', file: 'zani.blocks.js', exportName: 'ZANI_BLOCKS' },
  { name: 'Zhezhi', file: 'zhezhi.blocks.js', exportName: 'ZHEZHI_BLOCKS' },
];

const BLOCKS_BY_NAME = {};
beforeAll(async () => {
  await Promise.all(BLOCK_FILES.map(async ({ name, file, exportName }) => {
    const base = file.replace(/\.blocks\.js$/, '');
    const mod = await import(`../engine/characterBlocks/${base}.blocks.js`);
    BLOCKS_BY_NAME[name] = mod[exportName];
  }));
});

// Reproduces calcTeamStats.js's RAW-tier gear-stat assembly (the private per-member rStats object
// built inside its own forEach loop) for a SOLO team's sole member — NOT imported, since it's not an
// exported function; same "reproduce the live file's own real formula, don't modify it for test
// plumbing" approach verifyEngineAgainstCalcTeamStats.test.js already established for
// overlapUptimeForSeg. RAW tier deliberately zeroes defIgnore/defShred regardless of gear (see that
// tier's own rStats literal in calcTeamStats.js) — reproduced here, not "fixed", to stay comparable.
function rawTierGearStats(name, weaponName, echoSetName, echoSet2Name) {
  const d = CHARACTER_DATA[name];
  const weapon = WEAPON_DATA[weaponName];
  const scaling = d.statScaling || 'ATK';
  let cr = 5, cd = 150, atkPct = 0, elemDmg = 0, skillDmg = 0, basicDmg = 0, heavyDmg = 0, libDmg = 0, echoDmg = 0;
  if (weapon?.stat === 'Crit Rate') cr += parseFloat(weapon.subStatValue) || 0;
  if (weapon?.stat === 'Crit DMG') cd += parseFloat(weapon.subStatValue) || 0;
  const statKey = scaling === 'HP' ? 'HP%' : scaling === 'DEF' ? 'DEF%' : 'ATK%';
  if (weapon?.stat === statKey) atkPct += parseFloat(weapon.subStatValue) || 0;
  const wp = getWeaponPv(weapon, d.element, 1);
  if (scaling === 'ATK') atkPct += (wp.atkPct || 0);
  else if (scaling === 'HP') atkPct += (wp.hpPct || 0);
  else if (scaling === 'DEF') atkPct += (wp.defPct || 0);
  elemDmg += (wp.elemDmg || 0); skillDmg += (wp.skillDmg || 0);
  cr += (wp.critRate || 0); cd += (wp.critDmg || 0);
  basicDmg += (wp.basicDmg || 0); heavyDmg += (wp.heavyDmg || 0);
  libDmg += (wp.libDmg || 0); echoDmg += (wp.echoDmg || 0);
  const rStats = { atkPct, cr, cd, elemDmg, skillDmg, basicDmg, heavyDmg, libDmg, echoDmg, deepen: 0, amplify: 0, defShred: 0, resShred: 0, defIgnore: 0 };
  const echoSet = echoSetName ? ECHO_SETS[echoSetName] : null;
  const echoSet2 = echoSet2Name ? ECHO_SETS[echoSet2Name] : null;
  applyFullEchoSet(rStats, echoSet, echoSet2, d.element, scaling);
  return rStats;
}

// externalStats for resolveHitComposedDps wants DELTAS (cr/cd NOT pre-seeded with the 5/150
// baseline — see resolveHitComposedDps.js's own EXTERNAL_STAT_KEYS comment), so cr/cd are
// re-based to 0 here before handing off.
function toExternalStatsDelta(rStats) {
  return { ...rStats, cr: rStats.cr - 5, cd: rStats.cd - 150 };
}

// Mirrors calcTeamStats.js's own "no echoes equipped → preview the recommended build's set bonus"
// branch (its per-member mapping's inline echoSetName inference), so a bare-kit case gets the SAME
// weapon+set calcTeamStats() itself actually used for its RAW tier.
function previewEchoSet(bestEchoes) {
  for (const e of bestEchoes || []) {
    const hybridMatch = e.match(/^(.+?)\s+3pc\s*\+\s*(.+?)\s+2pc$/i);
    if (hybridMatch) {
      const s1 = hybridMatch[1].trim(), s2 = hybridMatch[2].trim();
      return { echoSet: ECHO_SETS[s1] ? s1 : '', echoSet2: ECHO_SETS[s2] ? s2 : '' };
    }
    const k = Object.keys(ECHO_SETS).find(k => e.includes(k));
    if (k) return { echoSet: k, echoSet2: '' };
  }
  return { echoSet: '', echoSet2: '' };
}

describe('PHASE3_PLAN.md Stage 1 — parity harness (engine hit-composed DPS vs. calcTeamStats RAW tier), all converted characters', () => {
  BLOCK_FILES.forEach(({ name }) => {
    it(`${name}: engine-composed solo damage vs. calcTeamStats() rawDps — logs real numbers for Stage 2 triage`, () => {
      const d = CHARACTER_DATA[name];
      const rotation = CHARACTER_ROTATIONS[name];
      const blocks = BLOCKS_BY_NAME[name];
      expect(blocks, `no blocks loaded for ${name}`).toBeTruthy();
      if (!rotation) {
        // A handful of converted characters may still lack a CHARACTER_ROTATIONS entry — nothing to
        // derive real steps from; log and skip rather than fail the whole sweep on a data gap that's
        // not this harness's job to fix.
          // eslint-disable-next-line no-console
        console.log(`[Stage1 parity] ${name}: SKIPPED — no CHARACTER_ROTATIONS entry`);
        return;
      }

      const { echoSet, echoSet2 } = previewEchoSet(d.bestEchoes);
      const weapon = d.bestWeapon;
      const teamIdx = 0;
      const teamEquipment = {}; // calcTeamStats() runs its own real preview inference from this

      const legacy = calcTeamStats([name], teamIdx, name, teamEquipment, '', 90);
      expect(legacy, `calcTeamStats() returned null for solo ${name}`).toBeTruthy();
      const legacyRawDps = legacy.rawDps;

      const scaling = d.statScaling || 'ATK';
      const usedWeapon = WEAPON_DATA[weapon];
      // Always supply all three raw base stats (not just the character's own scaling stat) — several
      // HP/DEF-scaling characters mix ATK-basis hits into an otherwise HP/DEF-scaling kit (same
      // documented pattern as Cartethyia's own audit comment on mixed "%"/"%HP" notation), so a block
      // needing a basis other than the character's main scaling stat still needs a real number, not a
      // thrown error. atkPct-style %-buffs (gear + kit) still only ever apply to the ATK-basis figure
      // per resolveHitComposedDps's own convention — this only fixes the "which raw number is
      // available at all" gap, not scaling routing.
      const baseStats = { atk: (d.baseAtk || 0) + (usedWeapon?.baseAtk || 0), hp: d.baseHp || 0, def: d.baseDef || 0 };
      const gearDelta = toExternalStatsDelta(rawTierGearStats(name, weapon, echoSet, echoSet2));

      let engineDps = 0, totalDamage = 0, totalTime = 0, threw = null;
      try {
        const steps = deriveStepsFromRotation(rotation, blocks);
        ({ totalDamage, totalTime } = resolveHitComposedDps(blocks, steps, { enemyDef: 792 + 8 * 90, enemyRes: 10 }, baseStats, (d.element || '').toLowerCase(), d.role, gearDelta));
        engineDps = totalTime > 0 ? totalDamage / totalTime : 0;
      } catch (err) {
        threw = err;
      }

      expect(legacyRawDps).toBeGreaterThan(0);

      if (threw) {
        // eslint-disable-next-line no-console
        console.log(`[Stage1 parity] ${name}: ENGINE THREW — ${threw.message}`);
        // A thrown error (e.g. a missing baseStats.hp/def for a block needing it) is itself a real
        // Stage 2 finding, not a harness failure to swallow — surface it, don't silently zero it out.
        expect(threw, `${name}: engine threw during hit composition — see console log above`).toBeNull();
        return;
      }

      expect(Number.isFinite(engineDps)).toBe(true);
      const ratio = legacyRawDps > 0 ? engineDps / legacyRawDps : Infinity;
      // eslint-disable-next-line no-console
      console.log(`[Stage1 parity] ${name}: calcTeamStats.rawDps=${Math.round(legacyRawDps)}  engine dps=${Math.round(engineDps)}  ratio(engine/legacy)=${ratio.toFixed(3)}  weapon=${weapon}`);
    });
  });
});
