// "Download for offline" API — character animations (portraits/, spine/) and
// banner videos (animated-bg/) into the service worker's ASSET_CACHE. Thin
// wrapper reusing the exact same download-overlay/purge-overlay/query-overlay
// SW messages tileSW.js uses for map tiles, just passing `cache: 'assets'` so
// the SW's generalized handlers (see public/sw.js) target ASSET_CACHE instead
// of TILE_CACHE — see that file for why they're kept separate (independent
// purge, no shared LRU).
//
// The manifest (app/public/dev/asset-manifest.json, generated by
// tools/build-asset-manifest.mjs at build time) lists every file actually
// shipped under those three directories — always accurate, no hand-maintained
// list to drift from the real contents.

const BASE_URL = (import.meta.env.BASE_URL || '/');

let _manifestPromise = null;
export function loadAssetManifest() {
  if (!_manifestPromise) {
    _manifestPromise = fetch(`${BASE_URL}dev/asset-manifest.json`)
      .then(r => { if (!r.ok) throw new Error(`manifest fetch failed: ${r.status}`); return r.json(); })
      .catch(err => { _manifestPromise = null; throw err; }); // allow retry on failure
  }
  return _manifestPromise;
}

export const ASSET_CATEGORY_LABELS = {
  portraits: 'Character Animations',
  spine: 'Banner Character Art',
  'animated-bg': 'Animated Banner Backgrounds',
};

function swController() {
  return navigator.serviceWorker?.controller || null;
}

function nextId(prefix) {
  return `${prefix}:${Date.now().toString(36)}:${Math.floor(Math.random() * 1e6).toString(36)}`;
}

const CALL_STALL_MS = 60_000;

function callSW(message, { matchId, terminal, onProgress }) {
  return new Promise((resolve, reject) => {
    const sw = swController();
    if (!sw) { reject(new Error('no-service-worker')); return; }

    let stallTimer = null;
    const resetStall = () => {
      if (stallTimer) clearTimeout(stallTimer);
      stallTimer = setTimeout(() => {
        navigator.serviceWorker.removeEventListener('message', handler);
        reject(new Error('service-worker-stalled'));
      }, CALL_STALL_MS);
    };

    const handler = (event) => {
      const msg = event.data;
      if (!msg || typeof msg !== 'object' || msg.id !== matchId) return;
      resetStall();
      if (onProgress && msg.type === 'download-progress') {
        onProgress(msg.done, msg.total, msg.failed || 0);
        return;
      }
      if (terminal.includes(msg.type)) {
        if (stallTimer) clearTimeout(stallTimer);
        navigator.serviceWorker.removeEventListener('message', handler);
        if (msg.type.endsWith('-error')) reject(new Error(msg.error || msg.type));
        else resolve(msg);
      }
    };
    navigator.serviceWorker.addEventListener('message', handler);
    resetStall();
    sw.postMessage(message);
  });
}

// category: one of ASSET_CATEGORY_LABELS' keys, or 'all' for every category combined.
export async function downloadAssets(category, onProgress) {
  const manifest = await loadAssetManifest();
  const urls = urlsForCategory(manifest, category);
  const id = nextId('dl-assets');
  const res = await callSW(
    { type: 'download-overlay', cache: 'assets', id, urls },
    { matchId: id, terminal: ['download-done', 'download-error'], onProgress }
  );
  return { total: res.total, failed: res.failed || 0 };
}

export async function purgeAssets(category) {
  const manifest = await loadAssetManifest();
  const urls = urlsForCategory(manifest, category);
  const id = nextId('rm-assets');
  await callSW(
    { type: 'purge-overlay', cache: 'assets', id, urls },
    { matchId: id, terminal: ['purge-done', 'purge-error'] }
  );
  return true;
}

export async function queryAssets(category) {
  const manifest = await loadAssetManifest();
  const urls = urlsForCategory(manifest, category);
  const id = nextId('q-assets');
  const res = await callSW(
    { type: 'query-overlay', cache: 'assets', id, urls },
    { matchId: id, terminal: ['query-result', 'query-error'] }
  );
  return { cached: res.cached, total: res.total };
}

function urlsForCategory(manifest, category) {
  const cats = category === 'all' ? Object.keys(manifest.categories) : [category];
  return cats.flatMap(c => (manifest.categories[c]?.files || []).map(f => f.url));
}

export function serviceWorkerAvailable() {
  return !!(navigator.serviceWorker && navigator.serviceWorker.controller);
}
