// ═══════════════════════════════════════════════════════════════════════════════
// WW Update Agent — Changelog Generator
//
// Generates a user-facing changelog from agent activity.
// Written to two places:
// 1. agent/CHANGELOG.md — full history in the repo
// 2. appcore-data.js CHANGELOG constant — visible to users in the app
//
// The app's Profile tab can display the latest entries from CHANGELOG.
// ═══════════════════════════════════════════════════════════════════════════════

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { PATHS } from './config.js';
import { log, addChange, getChangeLog } from './log.js';

const CHANGELOG_FILE = resolve(PATHS.repoRoot, 'agent/CHANGELOG.md');
const MAX_APP_ENTRIES = 15; // Show last 15 entries in the app

/**
 * Generate changelog entries from the current run's changes.
 * Returns human-readable entries.
 */
export function generateEntries(mode, appVersion) {
  const changes = getChangeLog();
  if (!changes.length) return [];

  const date = new Date().toISOString().split('T')[0];
  const entries = [];

  // Group changes by category
  const grouped = {};
  for (const c of changes) {
    const cat = humanCategory(c.category);
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push(c.description);
  }

  for (const [category, descriptions] of Object.entries(grouped)) {
    // Deduplicate and clean up
    const unique = [...new Set(descriptions)];
    for (const desc of unique) {
      entries.push({
        date,
        version: appVersion,
        category,
        description: cleanDescription(desc),
      });
    }
  }

  return entries;
}

/**
 * Append entries to CHANGELOG.md.
 */
export function appendToChangelog(entries, appVersion) {
  if (!entries.length) return;

  const date = entries[0].date;

  let existing = '';
  if (existsSync(CHANGELOG_FILE)) {
    existing = readFileSync(CHANGELOG_FILE, 'utf-8');
  } else {
    existing = `# Whispering Wishes — Changelog

Auto-generated by the WW Update Agent.

`;
  }

  // Check if we already have an entry for this date+version
  if (existing.includes(`## v${appVersion} — ${date}`)) {
    // Append to existing section
    const sectionEnd = existing.indexOf('\n## ', existing.indexOf(`## v${appVersion} — ${date}`) + 1);
    const insertPoint = sectionEnd === -1 ? existing.length : sectionEnd;

    const newLines = entries.map(e => `- **${e.category}**: ${e.description}`).join('\n');
    existing = existing.slice(0, insertPoint) + '\n' + newLines + existing.slice(insertPoint);
  } else {
    // New section
    const section = `## v${appVersion} — ${date}\n\n${entries.map(e => `- **${e.category}**: ${e.description}`).join('\n')}\n\n`;

    // Insert after the header
    const headerEnd = existing.indexOf('\n\n', existing.indexOf('# '));
    if (headerEnd !== -1) {
      existing = existing.slice(0, headerEnd + 2) + section + existing.slice(headerEnd + 2);
    } else {
      existing += section;
    }
  }

  writeFileSync(CHANGELOG_FILE, existing);
  log.ok(`Changelog updated: ${entries.length} entries`);
}

/**
 * Update the CHANGELOG array in appcore-data.js for in-app display.
 * If no CHANGELOG constant exists, creates one.
 */
export function updateAppChangelog(entries, getBufferFn, loadBufferFn) {
  if (!entries.length) return false;

  let buf = getBufferFn();

  // Build new entries
  const newEntries = entries.map(e =>
    `  { date: '${e.date}', category: '${e.category}', text: '${e.description.replace(/'/g, "\\'")}' }`
  );

  // Check if CHANGELOG constant exists
  const existingMatch = buf.match(/const CHANGELOG\s*=\s*\[([\s\S]*?)\];\s*\n/);

  if (existingMatch) {
    // Parse existing entries and prepend new ones
    const existingEntries = existingMatch[1].trim();
    const allEntries = newEntries.join(',\n') + (existingEntries ? ',\n' + existingEntries : '');

    // Trim to MAX_APP_ENTRIES
    const trimmed = allEntries.split('\n')
      .filter(l => l.trim().startsWith('{'))
      .slice(0, MAX_APP_ENTRIES)
      .join(',\n');

    const newBlock = `const CHANGELOG = [\n${trimmed}\n];\n`;
    buf = buf.replace(existingMatch[0], newBlock);
  } else {
    // Create CHANGELOG constant before the exports
    const exportMarker = '\n// ═══════════════════════════════════════════════════════════════════════════════\n// EXPORTS';

    if (buf.includes(exportMarker)) {
      const changelogBlock = `\n// [SECTION:CHANGELOG]\nconst CHANGELOG = [\n${newEntries.join(',\n')}\n];\n`;
      buf = buf.replace(exportMarker, changelogBlock + exportMarker);

      // Also add to exports
      const exportMatch = buf.match(/(export \{[\s\S]*?)(};)/);
      if (exportMatch && !exportMatch[1].includes('CHANGELOG')) {
        buf = buf.replace(exportMatch[0], `${exportMatch[1]}  CHANGELOG,\n${exportMatch[2]}`);
      }
    }
  }

  loadBufferFn(buf);
  return true;
}

// ═══════════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════════

function humanCategory(cat) {
  const map = {
    'banners': 'Banners',
    'banner-images': 'Banners',
    'events': 'Events',
    'characters': 'Resonators',
    'weapons': 'Weapons',
    'enrichment': 'Data',
    'data-enrichment': 'Data',
    'meta-refresh': 'Builds',
    'standard-pool': 'Standard Pool',
    'images': 'Images',
    'health': 'Maintenance',
    'version': 'Version',
    'evolution': 'Agent',
    'evolution-create': 'Agent',
    'shell-swap': 'Agent',
    'ui-polish': 'UI',
    'bugfix': 'Fixes',
    'code-quality': 'Code',
    'feature': 'Features',
    'a11y': 'Accessibility',
    'rollback-warning': 'Warning',
  };
  return map[cat] || cat;
}

function cleanDescription(desc) {
  // Remove technical prefixes and make user-friendly
  return desc
    .replace(/^\[evolution\]\s*/i, '')
    .replace(/^Shell-swap:\s*/i, '')
    .replace(/^Bump version\s*/i, 'Updated to ')
    .replace(/^Added\s+/i, 'Added ')
    .replace(/^Updated\s+/i, 'Updated ')
    .replace(/→/g, '→')
    .slice(0, 120);
}
