// ═══════════════════════════════════════════════════════════════════════════════
// WW Update Agent — Git Operations
// Handles branching, committing, pushing, and action logging.
// Branch: WW-B_maintenance_(x)  |  Action log: WW-B_comment_(x)
// ═══════════════════════════════════════════════════════════════════════════════

import { execSync, execFileSync } from 'child_process';
import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { PATHS, GIT } from './config.js';
import { log, getChangeLog } from './log.js';

const exec = (cmd) => execSync(cmd, { cwd: PATHS.repoRoot, encoding: 'utf-8', stdio: 'pipe' }).trim();

// ─── Action Log ─────────────────────────────────────────────────────────────
// Accumulates all actions taken during a run, written to WW-B_comment_(x)
const _actionLog = [];

export function logAction(category, description, details = null) {
  const entry = {
    time: new Date().toISOString(),
    category,
    description,
    ...(details ? { details } : {}),
  };
  _actionLog.push(entry);
}

function writeActionLog(runNumber) {
  const filename = `WW-B_comment_${runNumber}.md`;
  const filepath = resolve(PATHS.repoRoot, filename);

  const changes = getChangeLog();
  const lines = [
    `# WW-B Maintenance Report #${runNumber}`,
    `**Date:** ${new Date().toISOString()}`,
    `**Agent:** WW-B (Groq / ${process.env.GROQ_MODEL || 'llama-3.3-70b-versatile'})`,
    '',
    '## Summary',
    `- **Actions taken:** ${_actionLog.length}`,
    `- **Changes applied:** ${changes.length}`,
    '',
    '## Changes',
    ...changes.map(c => `- [${c.category}] ${c.description} (confidence: ${c.confidence})`),
    '',
    '## Action Log',
    ...(_actionLog.length ? _actionLog.map(a =>
      `### ${a.time} — [${a.category}] ${a.description}${a.details ? '\n```\n' + (typeof a.details === 'string' ? a.details : JSON.stringify(a.details, null, 2)) + '\n```' : ''}`
    ) : ['No actions taken.']),
    '',
  ];

  writeFileSync(filepath, lines.join('\n'), 'utf-8');
  log.ok(`Action log written: ${filename}`);
  return filename;
}

// ─── Git Operations ─────────────────────────────────────────────────────────

export function checkGitStatus() {
  try {
    exec('git status --short');
    return true;
  } catch {
    log.warn('Git not available or not in a git repo');
    return false;
  }
}

export function configureGit() {
  try {
    exec(`git config user.name "${GIT.authorName}"`);
    exec(`git config user.email "${GIT.authorEmail}"`);
    log.ok(`Git configured: ${GIT.authorName} <${GIT.authorEmail}>`);
  } catch (err) {
    log.warn(`Could not configure git: ${err.message}`);
  }
}

/**
 * Find the next run number by checking existing WW-B_maintenance_ branches.
 */
function getNextRunNumber() {
  try {
    const branches = exec('git branch -a --list *WW-B_maintenance_*');
    if (!branches) return 1;
    const numbers = branches
      .split('\n')
      .map(b => b.trim().replace(/.*WW-B_maintenance_/, ''))
      .map(n => parseInt(n, 10))
      .filter(n => !isNaN(n));
    return numbers.length ? Math.max(...numbers) + 1 : 1;
  } catch {
    return 1;
  }
}

/**
 * Create and checkout WW-B_maintenance_(x) branch.
 * Must be called BEFORE any modifications.
 */
export function createBranch() {
  const runNumber = getNextRunNumber();
  const branch = `${GIT.branchPrefix}${runNumber}`;

  try {
    exec(`git checkout -b ${branch}`);
    log.ok(`Created branch: ${branch}`);
    logAction('git', `Created branch ${branch}`);
    return { branch, runNumber };
  } catch (err) {
    log.error(`Failed to create branch: ${err.message}`);
    return { branch: null, runNumber };
  }
}

export function commitChanges(summary, runNumber) {
  try {
    // Stage app files
    exec('git add app/src/appcore-data.js');
    exec('git add app/package.json');
    exec('git add app/public/sw.js');

    // Write and stage the action log
    const commentFile = writeActionLog(runNumber);
    exec(`git add ${commentFile}`);

    const status = exec('git status --short');
    if (!status) {
      log.info('No changes to commit');
      return null;
    }

    const changes = getChangeLog();
    const changeLines = changes.map(c => `  - [${c.category}] ${c.description} (${c.confidence})`).join('\n');
    const message = `${GIT.commitPrefix} ${summary}\n\nChanges:\n${changeLines}\n\nGenerated by WW-B at ${new Date().toISOString()}`;

    execFileSync('git', ['commit', '-m', message], {
      cwd: PATHS.repoRoot,
      encoding: 'utf-8',
      stdio: 'pipe',
    });

    const hash = exec('git rev-parse --short HEAD');
    log.ok(`Committed: ${hash} — ${summary}`);
    logAction('git', `Committed ${hash}: ${summary}`);
    return hash;
  } catch (err) {
    log.error(`Commit failed: ${err.message}`);
    return null;
  }
}

export function pushBranch(branch) {
  try {
    exec(`git push origin ${branch}`);
    log.ok(`Pushed branch: ${branch}`);
    logAction('git', `Pushed ${branch}`);
    return true;
  } catch (err) {
    log.error(`Push failed: ${err.message}`);
    return false;
  }
}

/**
 * Full git workflow: branch → commit → push
 * Branch is created BEFORE any work, commit happens AFTER.
 */
export function gitPublish(summary, runNumber) {
  const commit = commitChanges(summary, runNumber);
  if (!commit) return { commit: null, pushed: false };

  const branch = `${GIT.branchPrefix}${runNumber}`;
  const pushed = pushBranch(branch);
  return { commit, pushed };
}

/**
 * Write ONLY the comment file and commit it — no code changes.
 * WW-B is audit-only: it compiles findings but never modifies app code.
 */
export function writeCommentOnly(runNumber) {
  try {
    const commentFile = writeActionLog(runNumber);
    exec(`git add ${commentFile}`);

    const status = exec('git status --short');
    if (!status) { log.info('No comment to commit'); return; }

    const message = `${GIT.commitPrefix} audit report #${runNumber}\n\nFindings compiled in ${commentFile}\nReview before applying any changes.\n\nGenerated by WW-B at ${new Date().toISOString()}`;

    execFileSync('git', ['commit', '-m', message], {
      cwd: PATHS.repoRoot,
      encoding: 'utf-8',
      stdio: 'pipe',
    });

    const hash = exec('git rev-parse --short HEAD');
    log.ok(`Comment committed: ${hash}`);

    const branch = `${GIT.branchPrefix}${runNumber}`;
    pushBranch(branch);
  } catch (err) {
    log.error(`Comment commit failed: ${err.message}`);
  }
}

/**
 * Create the working branch before any modifications.
 * Returns { branch, runNumber } or exits on failure.
 */
export function initBranch() {
  if (!checkGitStatus()) return { branch: null, runNumber: 0 };
  configureGit();
  return createBranch();
}
