// ═══════════════════════════════════════════════════════════════════════════════
// WW Update Agent — Git Operations
// Handles branching, committing, and pushing updates.
// ═══════════════════════════════════════════════════════════════════════════════

import { execSync, execFileSync } from 'child_process';
import { PATHS, GIT } from './config.js';
import { log, getChangeLog } from './log.js';

const exec = (cmd) => execSync(cmd, { cwd: PATHS.repoRoot, encoding: 'utf-8', stdio: 'pipe' }).trim();

/**
 * Check if git is available and repo is clean-ish.
 */
export function checkGitStatus() {
  try {
    exec('git status --short');
    return true;
  } catch {
    log.warn('Git not available or not in a git repo');
    return false;
  }
}

/**
 * Configure git author for the agent.
 */
export function configureGit() {
  try {
    exec(`git config user.name "${GIT.authorName}"`);
    exec(`git config user.email "${GIT.authorEmail}"`);
    log.ok(`Git configured: ${GIT.authorName} <${GIT.authorEmail}>`);
  } catch (err) {
    log.warn(`Could not configure git: ${err.message}`);
  }
}

/**
 * Create and checkout a new branch for this update.
 * Branch name format: auto-update/YYYY-MM-DD-HHMMSS
 */
export function createBranch() {
  const now = new Date();
  const stamp = now.toISOString().replace(/[:-]/g, '').replace('T', '-').slice(0, 15);
  const branch = `${GIT.branchPrefix}${stamp}`;

  try {
    exec(`git checkout -b ${branch}`);
    log.ok(`Created branch: ${branch}`);
    return branch;
  } catch (err) {
    log.error(`Failed to create branch: ${err.message}`);
    return null;
  }
}

/**
 * Stage and commit all changes.
 * Returns the commit hash or null on failure.
 */
export function commitChanges(summary) {
  try {
    // Stage the specific files we modify
    exec('git add whispering-wishes-replit/src/appcore-data.js');
    exec('git add whispering-wishes-replit/package.json');
    exec('git add whispering-wishes-replit/public/sw.js');

    // Check if there's anything to commit
    const status = exec('git status --short');
    if (!status) {
      log.info('No changes to commit');
      return null;
    }

    // Build commit message from change log
    const changes = getChangeLog();
    const changeLines = changes.map(c => `  - [${c.category}] ${c.description} (${c.confidence})`).join('\n');

    const message = `${GIT.commitPrefix} ${summary}\n\nChanges:\n${changeLines}\n\nGenerated by WW Update Agent at ${new Date().toISOString()}`;

    execFileSync('git', ['commit', '-m', message], {
      cwd: PATHS.repoRoot,
      encoding: 'utf-8',
      stdio: 'pipe',
    });

    const hash = exec('git rev-parse --short HEAD');
    log.ok(`Committed: ${hash} — ${summary}`);
    return hash;
  } catch (err) {
    log.error(`Commit failed: ${err.message}`);
    return null;
  }
}

/**
 * Push the current branch to origin.
 */
export function pushBranch(branch) {
  try {
    exec(`git push origin ${branch}`);
    log.ok(`Pushed branch: ${branch}`);
    return true;
  } catch (err) {
    log.error(`Push failed: ${err.message}`);
    return false;
  }
}

/**
 * Full git workflow: branch → commit → push
 */
export function gitPublish(summary) {
  if (!checkGitStatus()) return { branch: null, commit: null, pushed: false };

  configureGit();
  const branch = createBranch();
  if (!branch) return { branch: null, commit: null, pushed: false };

  const commit = commitChanges(summary);
  if (!commit) return { branch, commit: null, pushed: false };

  const pushed = pushBranch(branch);
  return { branch, commit, pushed };
}
