// "Download for offline" API — every local asset directory (portraits/,
// spine/, animated-bg/, convene-animations/ — excluded from the native
// (Capacitor) app bundle, see capacitor-build/build.mjs's EXCLUDED_DIRS —
// plus characters/, banners/, echoes/, materials/, misc-assets/,
// achievements/, ui-icons/, which *are* already bundled natively but are
// still lazily fetched on the web build) plus hotlinked third-party icon
// URLs, into the service worker's ASSET_CACHE. Thin wrapper reusing the
// exact same download-overlay/purge-overlay/query-overlay SW messages
// tileSW.js uses for map tiles, just passing `cache: 'assets'` so the SW's
// generalized handlers (see public/sw.js) target ASSET_CACHE instead of
// TILE_CACHE — see that file for why they're kept separate (independent
// purge, no shared LRU).
//
// The manifest (app/public/dev/asset-manifest.json, generated by
// tools/build-asset-manifest.mjs at build time) lists every file actually
// shipped under those directories — always accurate, no hand-maintained
// list to drift from the real contents.

const BASE_URL = (import.meta.env.BASE_URL || '/');

// Same fix apiBase.js applies to /api/*: inside the Capacitor native app the
// bundle is served from capacitor://localhost (iOS) / https://localhost
// (Android), which has no files under it at all — a relative '/portraits/...'
// fetch 404s instantly against that origin. portraits/spine/animated-bg were
// deliberately left out of the native bundle (see CAPACITOR_APP.md) and
// dist-native/sw.js's *fetch* listener already redirects normal page loads
// of those paths to VITE_API_BASE_URL, but handleDownloadOverlay's bulk
// fetch() calls run inside the SW script itself and never go through that
// listener, so they need the absolute URL up front. Icon URLs from
// src/data/*.js are already absolute (hotlinked from third-party hosts) and
// pass through untouched.
const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');
const isNativePlatform = () =>
  typeof window !== 'undefined' && !!window.Capacitor?.isNativePlatform?.();

function resolveDownloadUrl(u) {
  if (isNativePlatform() && API_BASE_URL && u.startsWith('/')) return API_BASE_URL + u;
  return u;
}

let _manifestPromise = null;
export function loadAssetManifest() {
  if (!_manifestPromise) {
    _manifestPromise = fetch(`${BASE_URL}dev/asset-manifest.json`)
      .then(r => { if (!r.ok) throw new Error(`manifest fetch failed: ${r.status}`); return r.json(); })
      .catch(err => { _manifestPromise = null; throw err; }); // allow retry on failure
  }
  return _manifestPromise;
}

export const ASSET_CATEGORY_LABELS = {
  portraits: 'Character Animations',
  spine: 'Banner Character Art',
  'animated-bg': 'Animated Banner Backgrounds',
  'convene-animations': 'Convene Animations',
  characters: 'Character Icons',
  banners: 'Banner Art',
  echoes: 'Echo Icons',
  materials: 'Material Icons',
  'misc-assets': 'Miscellaneous Assets',
  achievements: 'Achievement Icons',
  'ui-icons': 'UI Icons',
  audio: 'Soundtrack',
  icons: 'Hotlinked Icons',
};

function swController() {
  return navigator.serviceWorker?.controller || null;
}

function nextId(prefix) {
  return `${prefix}:${Date.now().toString(36)}:${Math.floor(Math.random() * 1e6).toString(36)}`;
}

const CALL_STALL_MS = 60_000;

function callSW(message, { matchId, terminal, onProgress }) {
  return new Promise((resolve, reject) => {
    const sw = swController();
    if (!sw) { reject(new Error('no-service-worker')); return; }

    let stallTimer = null;
    const resetStall = () => {
      if (stallTimer) clearTimeout(stallTimer);
      stallTimer = setTimeout(() => {
        navigator.serviceWorker.removeEventListener('message', handler);
        reject(new Error('service-worker-stalled'));
      }, CALL_STALL_MS);
    };

    const handler = (event) => {
      const msg = event.data;
      if (!msg || typeof msg !== 'object' || msg.id !== matchId) return;
      resetStall();
      if (onProgress && msg.type === 'download-progress') {
        onProgress(msg.done, msg.total, msg.failed || 0);
        return;
      }
      if (terminal.includes(msg.type)) {
        if (stallTimer) clearTimeout(stallTimer);
        navigator.serviceWorker.removeEventListener('message', handler);
        if (msg.type.endsWith('-error')) reject(new Error(msg.error || msg.type));
        else resolve(msg);
      }
    };
    navigator.serviceWorker.addEventListener('message', handler);
    resetStall();
    sw.postMessage(message);
  });
}

// category: one of ASSET_CATEGORY_LABELS' keys, or 'all' for every category combined.
export async function downloadAssets(category, onProgress) {
  const manifest = await loadAssetManifest();
  const urls = urlsForCategory(manifest, category);
  const id = nextId('dl-assets');
  const res = await callSW(
    { type: 'download-overlay', cache: 'assets', id, urls },
    { matchId: id, terminal: ['download-done', 'download-error'], onProgress }
  );
  return { total: res.total, failed: res.failed || 0 };
}

export async function purgeAssets(category) {
  const manifest = await loadAssetManifest();
  const urls = urlsForCategory(manifest, category);
  const id = nextId('rm-assets');
  await callSW(
    { type: 'purge-overlay', cache: 'assets', id, urls },
    { matchId: id, terminal: ['purge-done', 'purge-error'] }
  );
  return true;
}

export async function queryAssets(category) {
  const manifest = await loadAssetManifest();
  const urls = urlsForCategory(manifest, category);
  const id = nextId('q-assets');
  const res = await callSW(
    { type: 'query-overlay', cache: 'assets', id, urls },
    { matchId: id, terminal: ['query-result', 'query-error'] }
  );
  return { cached: res.cached, total: res.total };
}

function urlsForCategory(manifest, category) {
  const cats = category === 'all' ? Object.keys(manifest.categories) : [category];
  return cats.flatMap(c => (manifest.categories[c]?.files || []).map(f => resolveDownloadUrl(f.url)));
}

export function serviceWorkerAvailable() {
  return !!(navigator.serviceWorker && navigator.serviceWorker.controller);
}
