// AUTO-GENERATED by tools/build-prerender-manifest.mjs.
// Do not edit manually — re-run the script (or `npm run build`) to refresh.
//
// Maps each character (sprite or banner) that has a pre-rendered idle loop
// on disk to its public asset URL plus a format hint (`tmf` for .tmf,
// `video` for .webm/.mp4, `image` for animated .webp). SpinePlayer reads
// this to pick <tmf-player> / <video> / <img> for the tier-0 swap-in;
// characters not listed here skip straight to live WebGL.

export const PRERENDERED_IDLE = Object.freeze({
  "portraits/zanni/Portraits_Zanni": { url: "portraits/zanni/Portraits_Zanni_idle.mp4", format: "video" },
  "spine/role_zanni/c_zanni_1": { url: "spine/role_zanni/c_zanni_1_idle.mp4", format: "video" },
});

// Lookup helper. For sprite entries we derive the key from the .skel URL.
// For banner entries (no skelUrl on the registry) we derive it from the
// surface-prefixed characterId — same shape SpinePlayer.jsx uses to build
// the live JSON URL.
export function getPrerenderedIdle(charData, characterId) {
  if (charData?.skelUrl) {
    const key = charData.skelUrl.replace(/^\/?/, '').replace(/\.skel$/, '');
    return PRERENDERED_IDLE[key] || null;
  }
  if (typeof characterId === 'string' && characterId.startsWith('banner:')) {
    const id = characterId.slice('banner:'.length);
    const key = `spine/role_${id}/c_${id}_1`;
    return PRERENDERED_IDLE[key] || null;
  }
  return null;
}
