// AUTO-GENERATED by tools/build-prerender-manifest.mjs.
// Do not edit manually — re-run the script (or `npm run build`) to refresh.
//
// Maps each sprite character that has a pre-rendered idle loop on disk to
// its public WebP URL. SpinePlayer consults this set to decide whether the
// tier-0 (animated WebP) path is available; characters not listed here
// skip straight to the live WebGL fallback.

export const PRERENDERED_IDLE_URLS = Object.freeze({
});

// Lookup helper: resolves a SPRITE_SPINE_CHARACTERS entry to its
// pre-rendered WebP URL (or null if no prerender exists).
export function getPrerenderedIdleUrl(charData) {
  if (!charData?.skelUrl) return null;
  // skelUrl is `portraits/<dir>/Portraits_<name>.skel`; strip the
  // leading "portraits/" and trailing ".skel" to form the lookup key.
  const key = charData.skelUrl.replace(/^portraits\//, '').replace(/\.skel$/, '');
  return PRERENDERED_IDLE_URLS[key] || null;
}
