// AUTO-GENERATED by tools/build-prerender-manifest.mjs.
// Do not edit manually — re-run the script (or `npm run build`) to refresh.
//
// Maps each character (sprite or banner) that has a pre-rendered idle loop
// on disk to its public asset URL plus a format hint (`tmf` for .tmf,
// `video` for .webm/.mp4, `image` for animated .webp). SpinePlayer reads
// this to pick <tmf-player> / <video> / <img> for the tier-0 swap-in;
// characters not listed here skip straight to live WebGL.

export const PRERENDERED_IDLE = Object.freeze({
  "portraits/aimisi/Portraits_Aimisi": { url: "portraits/aimisi/Portraits_Aimisi_idle.mp4", format: "video" },
  "portraits/anke/Portraits_Anke": { url: "portraits/anke/Portraits_Anke_idle.mp4", format: "video" },
  "portraits/aogusita/Portraits_Aogusita": { url: "portraits/aogusita/Portraits_Aogusita_idle.mp4", format: "video" },
  "portraits/baizhi/Portraits_Baizhi": { url: "portraits/baizhi/Portraits_Baizhi_idle.mp4", format: "video" },
  "portraits/bulante/Portraits_Bulante": { url: "portraits/bulante/Portraits_Bulante_idle.mp4", format: "video" },
  "portraits/buling/Portraits_Buling": { url: "portraits/buling/Portraits_Buling_idle.mp4", format: "video" },
  "portraits/changli/Portraits_Changli": { url: "portraits/changli/Portraits_Changli_idle.mp4", format: "video" },
  "portraits/chun/Portraits_Chun": { url: "portraits/chun/Portraits_Chun_idle.mp4", format: "video" },
  "portraits/daniya/Portraits_Daniya": { url: "portraits/daniya/Portraits_Daniya_idle.mp4", format: "video" },
  "portraits/danjin/Portraits_Danjin": { url: "portraits/danjin/Portraits_Danjin_idle.mp4", format: "video" },
  "portraits/dengdeng/Portraits_Dengdeng": { url: "portraits/dengdeng/Portraits_Dengdeng_idle.mp4", format: "video" },
  "portraits/feibi/Portraits_Feibi": { url: "portraits/feibi/Portraits_Feibi_idle.mp4", format: "video" },
  "portraits/feixue/Portraits_Feixue": { url: "portraits/feixue/Portraits_Feixue_idle.mp4", format: "video" },
  "portraits/fuluoluo/Portraits_Fuluoluo": { url: "portraits/fuluoluo/Portraits_Fuluoluo_idle.mp4", format: "video" },
  "portraits/jiabeilina/Portraits_Jiabeilina": { url: "portraits/jiabeilina/Portraits_Jiabeilina_idle.mp4", format: "video" },
  "portraits/jianxin/Portraits_Jianxin": { url: "portraits/jianxin/Portraits_Jianxin_idle.mp4", format: "video" },
  "portraits/jinxi/Portraits_Jinxi": { url: "portraits/jinxi/Portraits_Jinxi_idle.mp4", format: "video" },
  "portraits/jiyan/Portraits_Jiyan": { url: "portraits/jiyan/Portraits_Jiyan_idle.mp4", format: "video" },
  "portraits/kakaluo/Portraits_Kakaluo": { url: "portraits/kakaluo/Portraits_Kakaluo_idle.mp4", format: "video" },
  "portraits/kanteleila/Portraits_Kanteleila": { url: "portraits/kanteleila/Portraits_Kanteleila_idle.mp4", format: "video" },
  "portraits/katixiya/Portraits_Katixiya": { url: "portraits/katixiya/Portraits_Katixiya_idle.mp4", format: "video" },
  "portraits/kelaita/Portraits_Kelaita": { url: "portraits/kelaita/Portraits_Kelaita_idle.mp4", format: "video" },
  "portraits/lingyang/Portraits_Lingyang": { url: "portraits/lingyang/Portraits_Lingyang_idle.mp4", format: "video" },
  "portraits/linnai/Portraits_Linnai": { url: "portraits/linnai/Portraits_Linnai_idle.mp4", format: "video" },
  "portraits/luhesi/Portraits_Luhesi": { url: "portraits/luhesi/Portraits_Luhesi_idle.mp4", format: "video" },
  "portraits/luokeke/Portraits_Luokeke": { url: "portraits/luokeke/Portraits_Luokeke_idle.mp4", format: "video" },
  "portraits/lupa/Portraits_Lupa": { url: "portraits/lupa/Portraits_Lupa_idle.mp4", format: "video" },
  "portraits/moning/Portraits_Moning": { url: "portraits/moning/Portraits_Moning_idle.mp4", format: "video" },
  "portraits/motefei/Portraits_Motefei": { url: "portraits/motefei/Portraits_Motefei_idle.mp4", format: "video" },
  "portraits/qianxiao/Portraits_Qianxiao": { url: "portraits/qianxiao/Portraits_Qianxiao_idle.mp4", format: "video" },
  "portraits/qiushui/Portraits_Qiushui": { url: "portraits/qiushui/Portraits_Qiushui_idle.mp4", format: "video" },
  "portraits/qiuyuan/Portraits_Qiuyuan": { url: "portraits/qiuyuan/Portraits_Qiuyuan_idle.mp4", format: "video" },
  "portraits/rover_female/Portraits_Female": { url: "portraits/rover_female/Portraits_Female_idle.mp4", format: "video" },
  "portraits/rover_male/Portraits_Male": { url: "portraits/rover_male/Portraits_Male_idle.mp4", format: "video" },
  "portraits/sanhua/Portraits_Sanhua": { url: "portraits/sanhua/Portraits_Sanhua_idle.mp4", format: "video" },
  "portraits/shouanren/Portraits_Shouanren": { url: "portraits/shouanren/Portraits_Shouanren_idle.mp4", format: "video" },
  "portraits/taoqi/Portraits_Taoqi": { url: "portraits/taoqi/Portraits_Taoqi_idle.mp4", format: "video" },
  "portraits/weilinai/Portraits_Weilinai": { url: "portraits/weilinai/Portraits_Weilinai_idle.mp4", format: "video" },
  "portraits/xiakong/Portraits_Xiakong": { url: "portraits/xiakong/Portraits_Xiakong_idle.mp4", format: "video" },
  "portraits/xiangliyao/Portraits_Xiangliyao": { url: "portraits/xiangliyao/Portraits_Xiangliyao_idle.mp4", format: "video" },
  "portraits/xigelika/Portraits_Xigelika": { url: "portraits/xigelika/Portraits_Xigelika_idle.mp4", format: "video" },
  "portraits/yangyang/Portraits_Yangyang": { url: "portraits/yangyang/Portraits_Yangyang_idle.mp4", format: "video" },
  "portraits/yinlin/Portraits_Yinlin": { url: "portraits/yinlin/Portraits_Yinlin_idle.mp4", format: "video" },
  "portraits/youhu/Portraits_Youhu": { url: "portraits/youhu/Portraits_Youhu_idle.mp4", format: "video" },
  "portraits/younuo/Portraits_Younuo": { url: "portraits/younuo/Portraits_Younuo_idle.mp4", format: "video" },
  "portraits/yuanwu/Portraits_Yuanwu": { url: "portraits/yuanwu/Portraits_Yuanwu_idle.mp4", format: "video" },
  "portraits/zanni/Portraits_Zanni": { url: "portraits/zanni/Portraits_Zanni_idle.mp4", format: "video" },
  "portraits/zhezhi/Portraits_Zhezhi": { url: "portraits/zhezhi/Portraits_Zhezhi_idle.mp4", format: "video" },
  "spine/role_zanni/c_zanni_1": { url: "spine/role_zanni/c_zanni_1_idle.mp4", format: "video" },
});

// Lookup helper. For sprite entries we derive the key from the .skel URL.
// For banner entries (no skelUrl on the registry) we derive it from the
// surface-prefixed characterId — same shape SpinePlayer.jsx uses to build
// the live JSON URL.
export function getPrerenderedIdle(charData, characterId) {
  if (charData?.skelUrl) {
    const key = charData.skelUrl.replace(/^\/?/, '').replace(/\.skel$/, '');
    return PRERENDERED_IDLE[key] || null;
  }
  if (typeof characterId === 'string' && characterId.startsWith('banner:')) {
    const id = characterId.slice('banner:'.length);
    const key = `spine/role_${id}/c_${id}_1`;
    return PRERENDERED_IDLE[key] || null;
  }
  return null;
}
